<?php

/**
 * @file
 * twig_svg functions.
 */

/**
 * Implements hook_preprocess_html().
 */
function twig_svg_preprocess_html(&$variables) {

  $active_theme = \Drupal::theme()->getActiveTheme();

  $themes = $active_theme->getBaseThemeExtensions();
  $themes[] = $active_theme;
  $icons = '';

  foreach ($themes as $theme) {
    $icon_path = $theme->getPath() . '/images/icons.svg';

    if (file_exists($icon_path)) {
      // Get the contents of the SVG sprite.
      $icons .= file_get_contents($icon_path);

      $variables['page_bottom']['icons'] = [
        '#type' => 'inline_template',
        '#template' => '<span class="hidden">' . $icons . '</span>',
      ];
    }
  }
}
